server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      timeout: PT15M


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: BlueBurger
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

volunteer:
  credit: 100

file:
  rootPath: "/root/Projects/Java/MovieBook"
  sonPath: "/img/"
  fileServer: "http://116.62.10.95:8000/uploadFiles/"

