
server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      timeout: PT15M


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.10.95:3306/Movie?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: movie_base
    password: 123456
    hikari:
      # 连接只读数据库时配置为true， 保证安全
      # read-only: true
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1770000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 100
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    ip: 123.57.22.40
    rest:
      uris: 123.57.22.40:9200

volunteer:
  credit: 100

file:
  rootPath: "/root/Projects/Java/MovieBook/img_server/webapps/ROOT"
  sonPath: "/uploadFiles/"
  fileServer: "http://localhost:8000/uploadFiles/"

